//Add one phone

POST http://localhost:8800/phones HTTP/1.1
Content-Type: application/json

{
    "name": "TCL 10 SE",
    "manufacturer": "Tcl",
    "description": "NXTVISION, Notch Gota, resistente a rayones",
    "color": "Black",
    "price": 190,
    "imageFileName": "tcl.png",
    "screen": "6,52 inch",
    "processor": "Helio P22",
    "ram": 4
}